#!/bin/tcsh
#PBS -N test_mpi4py_n2_ppn2
#PBS -l nodes=5:vortex:ppn=12
#PBS -l walltime=1:00:00

# init conda within new shell for job
source "/usr/local/anaconda3-2021.05/etc/profile.d/conda.csh"

module load anaconda3/2021.05
module load openmpi/3.1.4/gcc-9.3.0

unsetenv PYTHONPATH

conda activate /sciclone/home20/hmbaier/claw/dhsrl

mpiexec -n 40 python /sciclone/home20/hmbaier/test/test.py

